# Generated by Django 5.0.3 on 2024-04-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_budget_project_created_at_project_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', '(Completed)')], default='Open', max_length=20),
        ),
    ]
